# Conda recipe
{% set data = load_setup_py_data() %}

package:
  name: varbio
  version: '{{ data['version'] }}'

source:
  path: ..

build:
  script: '{{ PYTHON }} -m pip install . -vv'

requirements:
  build:
    - pip
    - python
  host:
    # Conda recommends always adding the interpreter as a host dep
    - python
  run:
    - python >=3.8
    - attrs
    - chardet
    - humanize
    - numpy >=1
    - pandas ==1.2.*
    - pyyaml
    - scipy

test:
  source_files:
    - pytest.ini
    - tests
  requires:
    - pytest >=3
    - pytil ==8.*
  commands:
    - pytest -l --tb=auto

about:
  home: https://github.com/timdiels/varbio
  license: LGPL3
  license_file: LICENSE.txt
  summary: Internal library with common code of coexpnetviz and morph
